<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Energy.Shared\Energy.Shared.csproj" />
      <ProjectReference Include="..\Energy.Domain\Energy.Domain.csproj" />
      <ProjectReference Include="..\Energy.Localization\Energy.Localization.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="14.1.0" />
    </ItemGroup>

</Project>
