<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Energy.Application\Energy.Application.csproj" />
      <ProjectReference Include="..\Energy.Shared\Energy.Shared.csproj" />
      <ProjectReference Include="..\Energy.Infrastructure\Energy.Infrastructure.csproj" />
      <ProjectReference Include="..\Energy.Localization\Energy.Localization.csproj" />
      <ProjectReference Include="..\Energy.Migrations.PostgreSql\Energy.Migrations.PostgreSql.csproj" />
      <ProjectReference Include="..\Energy.Migrations.SqlServer\Energy.Migrations.SqlServer.csproj" />
    </ItemGroup>

</Project>
