<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Energy.Shared\Energy.Shared.csproj" />
    <ProjectReference Include="..\Energy.Localization\Energy.Localization.csproj" />
    <PackageReference Include="DevExtreme.AspNet.Core" Version="25.2.7" />
    <PackageReference Include="DevExtreme.AspNet.Data" Version="5.1.0" />
  </ItemGroup>
  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\bootstrap.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\bootstrap.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx-diagram.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx-diagram.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx-gantt.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx-gantt.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.carmine.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.carmine.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.contrast.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.contrast.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.darkmoon.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.darkmoon.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.darkviolet.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.darkviolet.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.blue.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.blue.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.blue.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.blue.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.saas.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.saas.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.saas.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.saas.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.greenmist.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.greenmist.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.blue.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.blue.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.blue.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.blue.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.lime.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.lime.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.lime.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.lime.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.orange.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.orange.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.orange.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.orange.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.purple.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.purple.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.purple.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.purple.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.teal.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.teal.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.teal.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.teal.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.softblue.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.softblue.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devicons\css\devicons.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devicons\fonts\devicons.eot" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devicons\fonts\devicons.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devicons\fonts\devicons.ttf" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devicons\fonts\devicons.woff" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-quill\dx-quill.core.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-quill\dx-quill.core.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-quill\dx-quill.core.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-quill\dx-quill.core.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-quill\dx-quill.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-quill\dx-quill.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-aspnet-data\dx.aspnet.data.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-aspnet-data\dx.aspnet.data.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devexpress-gantt\dx-gantt.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devexpress-gantt\dx-gantt.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devexpress-gantt\dx-gantt.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devexpress-gantt\dx-gantt.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\dev-timer\ES\Timer.d.ts" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\dev-timer\ES\Timer.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\dev-timer\ES\Timer.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\dev-timer\Timer.d.ts" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\dev-timer\Timer.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\dev-timer\Timer.min.js" />
  </ItemGroup>
</Project>