<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Energy.Shared\Energy.Shared.csproj" />
    <ProjectReference Include="..\Energy.Localization\Energy.Localization.csproj" />
    <PackageReference Include="DevExtreme.AspNet.Core" Version="25.2.7" />
    <PackageReference Include="DevExtreme.AspNet.Data" Version="5.1.0" />
  </ItemGroup>
  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\bootstrap.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\bootstrap.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx-diagram.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx-diagram.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx-gantt.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx-gantt.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.carmine.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.carmine.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.contrast.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.contrast.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.darkmoon.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.darkmoon.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.darkviolet.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.darkviolet.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.blue.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.blue.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.blue.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.blue.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.saas.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.saas.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.saas.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.fluent.saas.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.greenmist.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.greenmist.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.blue.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.blue.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.blue.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.blue.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.lime.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.lime.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.lime.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.lime.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.orange.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.orange.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.orange.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.orange.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.purple.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.purple.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.purple.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.purple.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.teal.dark.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.teal.dark.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.teal.light.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.material.teal.light.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.softblue.compact.css" />
    <_ContentIncludedByDefault Remove="wwwroot\css\devextreme\dx.softblue.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devicons\css\devicons.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devicons\fonts\devicons.eot" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devicons\fonts\devicons.svg" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devicons\fonts\devicons.ttf" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devicons\fonts\devicons.woff" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-quill\dx-quill.core.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-quill\dx-quill.core.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-quill\dx-quill.core.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-quill\dx-quill.core.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-quill\dx-quill.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-quill\dx-quill.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-aspnet-data\dx.aspnet.data.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devextreme-aspnet-data\dx.aspnet.data.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devexpress-gantt\dx-gantt.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devexpress-gantt\dx-gantt.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devexpress-gantt\dx-gantt.min.css" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\devexpress-gantt\dx-gantt.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\dev-timer\ES\Timer.d.ts" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\dev-timer\ES\Timer.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\dev-timer\ES\Timer.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\dev-timer\Timer.d.ts" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\dev-timer\Timer.js" />
    <_ContentIncludedByDefault Remove="wwwroot\lib\dev-timer\Timer.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\aspnet\dx.aspnet.data.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\aspnet\dx.aspnet.mvc.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\bootstrap.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\bootstrap.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx-diagram.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx-diagram.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx-exceljs-fork.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx-exceljs-fork.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx-gantt.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx-gantt.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx-quill.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx-quill.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx.ai-integration.debug.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx.ai-integration.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx.all.debug.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx.all.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx.custom.debug.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx.viz.debug.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx.viz.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx.web.debug.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\dx.web.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\FileSaver.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\FileSaver.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\jquery.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\jquery.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\jspdf.plugin.autotable.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\jspdf.plugin.autotable.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\jspdf.umd.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\jspdf.umd.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\jszip.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\jszip.min.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.ar.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.bg.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.ca.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.cs.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.da.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.de.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.el.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.en.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.es.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.fa.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.fi.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.fr.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.hu.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.it.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.ja.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.lt.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.lv.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.nb.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.nl.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.pl.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.pt.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.ro.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.ru.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.sl.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.sv.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.tr.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.uk.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.vi.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.zh-tw.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\localization\dx.messages.zh.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\vectormap-data\africa.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\vectormap-data\canada.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\vectormap-data\eurasia.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\vectormap-data\europe.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\vectormap-data\usa.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\vectormap-data\world.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\vectormap-utils\dx.vectormaputils.debug.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\vectormap-utils\dx.vectormaputils.js" />
    <_ContentIncludedByDefault Remove="wwwroot\js\devextreme\vectormap-utils\dx.vectormaputils.node.js" />
  </ItemGroup>
</Project>